#! /bin/sh
### BEGIN INIT INFO
# Provides:             jw-led
# Required-Start:
# Required-Stop:        jw-sysmon
# Default-Start:        2
# Default-Stop:         0 1 6
# Short-Description:    jw led
# Description:          led ctl daemon
### END INIT INFO

export "PATH=/usr/local/bin"

LED_DAEMON="/usr/local/bin/led-ctl-daemon"
LED_PID="/var/run/led.pid"

. /lib/lsb/init-functions

__start_daemon()
{
    local _pid="$1"
    local _cmd="$2"

    start-stop-daemon --make-pidfile --pidfile $_pid --background --start \
        --exec $_cmd -- -t 2U
    [$? -eq 0] && echo "$(basename "$_cmd") started." && return
    echo "$(basename "$_cmd") start fail1 retcode: $?"
}

do_start()
{
    __start_daemon $LED_PID $LED_DAEMON
}

do_stop()
{
    killproc -p $LED_PID $(basename $LED_DAEMON)
}

do_status()
{
    status_of_proc -p $LED_PID $LED_DAEMON $(basename $LED_DAEMON) $(basename $LED_DAEMON)
}

apps_usage()
{
    echo "Usage: $(basename "$0") {start|stop|restart|status}"
}

case "${1:-}" in
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    status)
        do_status
        ;;
    *)
        apps_usage
        ;;
esac
exit 0
